#!/bin/sh


swallow() {
	addedtodesktop=$2
	lasttermdesktop=$(bspc query -D -n last)

	swallowerid=$1
	swallowingid=$(bspc query -N -n last)

	swallowerpid=$(xprop -id $swallowerid -notype _NET_WM_PID | awk '{print $3}')
	
	
	if [ "$addedtodesktop" = "$lasttermdesktop" ] && grep -q "$swallowerpid" /tmp/swallowpids; then
		echo "$swallowerid $swallowingid" >> /tmp/swallowids
		bspc node "$swallowingid" --flag hidden=on
	fi
}

spit() {
	spitterid=$1
	spitterdesktop=$2
	grep "^$spitterid" /tmp/swallowids || return
	spittingid=$(grep "^$spitterid" /tmp/swallowids | head -n1 | awk '{print $2}')

	bspc node "$spittingid" --flag hidden=off

	termdesktop=$(bspc query -D -n "$spittingid")
	[ "$termdesktop" = "$spitterdesktop" ] || bspc node "$spittingid" -d "$spitterdesktop"

	bspc node "$spittingid" -f
	sed -i "/^$spitterid/d" /tmp/swallowids
}

bspc_subscribe() {
    bspc subscribe node_add node_remove node_swap | while read -r event
    do
	case $(echo "$event" | awk '{ print $1 }') in
	    node_add)
		swallow $(echo "$event" | awk '{print $5 " " $3}')
		;;
	    node_remove)
		spit $(echo "$event" | awk '{print $4 " " $3}')
		;;
	esac
    done
}

launch() {
    $* &

    lpid=$!
    echo $lpid >> /tmp/swallowpids
    wait $lpid

    sed -i "/$lpid/d" /tmp/swallowpids
}

if [ $# -gt 0 ]; then
    launch $*
else
    bspc_subscribe
fi
